clc;
clear all;
clf;

global G a b var tolerancia iteraciones x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 X1 X2 X3 X4 X5 X6 X7 X8 X9 X10 e p resultado ERROR

G=0;
uicontrol('Style','push','position',[5 50 110 35],...
'String','Calcular','CallBack','Calculos');

uicontrol('Style','push','position',[180 50 110 35],...
'String','Terminar','CallBack','close');

uicontrol('Style','text','position',[135 380 60 35],...
'String','tolerancia');

uicontrol('Style','text','position',[280 200 160 40],...
'String','         Andrea Davila Lopera                        Daniel Hoyos                     Juan David Toro        ');

tol=uicontrol('Style','edit','position',[135 372 60 25],'CallBack',[...
    'tolerancia=str2num(get(tol,''string''));']);

uicontrol('Style','text','position',[210 380 60 35],...
'String','iteraciones');

n=uicontrol('Style','edit','position',[210 372 60 25],'CallBack',[...
    'iteraciones=str2num(get(n,''string''));']);

uicontrol('style','text','string','seleccione el metodo',...
    'position',[280 380 90 35]);

Jacobi=uicontrol('style','radio','string','jacobi',...
    'position',[280 356 90 35],'value',1,'CallBack',[...
    'set(Jacobi,''value'',1),'...
    'set(Gauss,''value'',0),'...
    'G=get(Gauss,''value'');']);

Gauss=uicontrol('style','radio','string','Gauss-Seidel',...
    'position',[280 334 90 35],...
    'CallBack',[...
    'set(Jacobi,''value'',0),'...
    'set(Gauss,''value'',1),'...
    'G=get(Gauss,''value'');']);

uicontrol('Style','text','position',[5 380 110 35],...
'String','numero de variables');

numvar=uicontrol('Style', 'popup',...
       'String', '2|3|4|5|6|7|8|9|10',...
       'Position', [5 360 110 35],'CallBack',['var=get(numvar,''value'')+1;,'...
       'for i=1:var,'...
            'b(i)=uicontrol(''Style'',''edit'',''position'',[265 (322-i*22) 20 20],''string'',''1'');,'...
            'for j=1:var,'...
                'a(i,j)=uicontrol(''Style'',''edit'',''position'',[(5+i*22) (322-j*22) 20 20],''string'',''1'');,'...
            'end,'...
       'end']);

