%DISEÑO DE FILTROS 
%TRABAJO FINAL CIRCUITOS II
%ROBINSON MONTES GOMEZ

function  MAIN();

lista1={'PASABAJAS' 'PASAALTAS' 'PASABANDA' 'RECHAZABANDA' };
lista2={'BUTTERWORTH' 'CHEVYSHEV'};

paginainicial=figure(...
    'Position',[70 40 680 530],...
    'Menubar','None',...
    'Tag','Principal',...
    'NumberTitle','off',...
    'resize','on',...
    'Name','DISEÑADOR DE FILTROS');

imagen=imread('filtro.jpg');
posit=[0 0 1 1];
eje=axes('Position',posit);
image(imagen);
axis off;
set(eje,'HandleVisibility','off');
    
titulo1=uicontrol(...
   	'Style','Text',...
	'BackgroundColor',[.2 .5 1], ...
    'Position',[90 443 500 45],...
    'FontSize',30,...
	'String','DISEÑADOR DE FILTROS',...
    'FontWeight','Bold');
 
tfrec1=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[80 220 105 20],...
    'FontSize',10,...
    'String','w1',...
    'FontWeight','Bold');
    
frec1=uicontrol(...
	'Style','Edit',...
    'Position',[190 220 80 20],...
    'Tag','fcia1',...
    'String','0',...
    'visible','on',...
	'FontWeight','Bold');

unidad1=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[275 220 20 20],...
    'FontSize',10,...
    'String','Hz',...
    'FontWeight','Bold');
    
tfrec2=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[80 190 105 20],...
    'Tag','tfcia2',...
    'String','w2',...
    'visible','off',...
    'FontWeight','Bold');

 frec2=uicontrol(...
    'Style','Edit',...
	'Position',[190 190 80 20],...
    'Tag','fcia2',...
    'String','0',...
    'visible','off',...
    'FontWeight','Bold');
       
 unidad2=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[275 190 20 20],...
    'FontSize',10,...
    'Tag','uni2',...
    'String','Hz',...
    'visible','off',...
    'FontWeight','Bold');
    
t2frec2=uicontrol(...
	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
	'Position',[140 165 105 20],...
    'visible','off',...
    'string','w1<w2',...
    'Tag','t2fcia2',...
    'FontWeight','Bold');

filtro=uicontrol(...
    'Style','popupmenu',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[80 175 215 95],...
    'String',lista1,...
    'callback','control',...
	'FontWeight','Bold',...
	'Tag','filt');

titulo2=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[220 285 275 20],...
    'FontSize',12,...
    'String','TIPO DE FILTRO',...
    'FontWeight','Bold');


metodo=uicontrol(...
    'Style','popupmenu',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[390 250 215 20],...
    'String',lista2,...
	'FontWeight','Bold',...
	'Tag','met');

titulo3=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[390 220 80 20],...
    'FontSize',10,...
    'String','Amax',...
    'FontWeight','Bold');
       
amax=uicontrol(...
	'Style','Edit',...
	'Position',[475 220 105 20],...
	'String','0',...
	'Tag','max',...
	'FontWeight','Bold');
        
 uidad3=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[585 220 20 20],...
    'FontSize',10,...
    'String','dB',...
    'visible','on',...
    'FontWeight','Bold');
 
titulo4=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[390 190 80 20],...
    'FontSize',10,...
    'String','Amin',...
    'FontWeight','Bold');
       
amin=uicontrol(...
	'Style','Edit',...
	'Position',[475 190 105 20],...
	'String','0',...
	'Tag','min',...
	'FontWeight','Bold');
        
 uidad4=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[585 190 20 20],...
    'FontSize',10,...
    'String','dB',...
    'visible','on',...
    'FontWeight','Bold');

titulo5=uicontrol(...
	'Style','Pushbutton',...
	'Position',[140 100 410 30],...
	'BackgroundColor',[.2 .5 1], ...
	'FontSize',15,...
    'String','DISEÑAR FILTRO',...
	'FontWeight','Bold',...
	'Callback','inicio;');
     
salir=uicontrol(...
	'Style','Pushbutton',...
	'BackgroundColor',[.2 .5 1], ...
	'Position',[260 40 190 25],...
	'String','SALIR',...
	'FontWeight','Bold',...
	'HandleVisibility','on',...
	'Callback','close;');
