%DISEÑO DE FILTROS 
%TRABAJO FINAL CIRCUITOS II
%ROBINSON MONTES GOMEZ

function  MAIN();
global fcia1 fcia2 tfcia2 t2fcia2 uni2 filt

lista1={'PASABAJAS' 'PASAALTAS' 'PASABANDA' 'RECHAZABANDA' };
lista2={'BUTTERWORTH' 'CHEVYSHEV'};

paginainicial=figure(...
    'Position',[70 40 680 530],...
    'Menubar','None',...
    'Tag','Principal',...
    'NumberTitle','off',...
    'resize','on',...
    'Name','DISEÑADOR DE FILTROS');

imagen=imread('filtro.jpg');
posit=[0 0 1 1];
eje=axes('Position',posit);
image(imagen);
axis off;
set(eje,'HandleVisibility','off');
    
titulo1=uicontrol(...
   	'Style','Text',...
	'BackgroundColor',[.2 .5 1], ...
    'Position',[90 443 500 45],...
    'FontSize',30,...
	'String','DISEÑADOR DE FILTROS',...
    'FontWeight','Bold');
 
tfrec1=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[80 220 105 20],...
    'FontSize',10,...
    'String','w1',...
    'FontWeight','Bold');
    
frec1=uicontrol(...
	'Style','Edit',...
    'Position',[190 220 80 20],...
    'Tag','fcia1',...
    'String','0',...
    'visible','on',...
	'FontWeight','Bold');

unidad1=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[275 220 20 20],...
    'FontSize',10,...
    'String','Hz',...
    'FontWeight','Bold');
    
tfrec2=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[80 190 105 20],...
    'Tag','tfcia2',...
    'String','w2',...
    'visible','off',...
    'FontWeight','Bold');

 frec2=uicontrol(...
    'Style','Edit',...
	'Position',[190 190 80 20],...
    'Tag','fcia2',...
    'String','0',...
    'visible','off',...
    'FontWeight','Bold');
       
 unidad2=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[275 190 20 20],...
    'FontSize',10,...
    'Tag','uni2',...
    'String','Hz',...
    'visible','off',...
    'FontWeight','Bold');
    
t2frec2=uicontrol(...
	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
	'Position',[140 165 105 20],...
    'visible','off',...
    'string','w1<w2',...
    'Tag','t2fcia2',...
    'FontWeight','Bold');

filtro=uicontrol(...
    'Style','popupmenu',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[80 175 215 95],...
    'String',lista1,...
    'callback','control',...
	'FontWeight','Bold',...
	'Tag','filt');

titulo2=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[220 285 275 20],...
    'FontSize',12,...
    'String','TIPO DE FILTRO',...
    'FontWeight','Bold');


metodo=uicontrol(...
    'Style','popupmenu',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[390 250 215 20],...
    'String',lista2,...
	'FontWeight','Bold',...
	'Tag','met');

titulo3=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[390 220 80 20],...
    'FontSize',10,...
    'String','Amax',...
    'FontWeight','Bold');
       
amax=uicontrol(...
	'Style','Edit',...
	'Position',[475 220 105 20],...
	'String','0',...
	'Tag','max',...
	'FontWeight','Bold');
        
 uidad3=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[585 220 20 20],...
    'FontSize',10,...
    'String','dB',...
    'visible','on',...
    'FontWeight','Bold');
 
titulo4=uicontrol(...
    'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[390 190 80 20],...
    'FontSize',10,...
    'String','Amin',...
    'FontWeight','Bold');
       
amin=uicontrol(...
	'Style','Edit',...
	'Position',[475 190 105 20],...
	'String','0',...
	'Tag','min',...
	'FontWeight','Bold');
        
 uidad4=uicontrol(...
 	'Style','Text',...
    'BackgroundColor',[.2 .5 1], ...
    'Position',[585 190 20 20],...
    'FontSize',10,...
    'String','dB',...
    'visible','on',...
    'FontWeight','Bold');

titulo5=uicontrol(...
	'Style','Pushbutton',...
	'Position',[140 100 410 30],...
	'BackgroundColor',[.2 .5 1], ...
	'FontSize',15,...
    'String','DISEÑAR FILTRO',...
	'FontWeight','Bold',...
	'Callback','inicio;');
     
salir=uicontrol(...
	'Style','Pushbutton',...
	'BackgroundColor',[.2 .5 1], ...
	'Position',[260 40 190 25],...
	'String','SALIR',...
	'FontWeight','Bold',...
	'HandleVisibility','on',...
	'Callback','close;');


a%DISEÑO DE FILTROS
%TRABAJO FINAL CIRCUITOS II
%ROBINSON MONTES GOMEZ

function control();
global fcia1 fcia2 tfcia2 t2fcia2 uni2 filt 


filt=findobj('tag','filt');
filt=get(filt,'value');
fcia1=findobj('tag','fcia1');
fcia2=findobj('tag','fcia2');
tfcia2=findobj('tag','tfcia2');
t2fcia2=findobj('tag','t2fcia2');
uni2=findobj('tag','uni2');


switch aprox
case 1,
   
   set(fcia1,'visible','on');
   set(fcia1,'string',0 );
   set(fcia2,'visible','off');
   set(tfcia2,'visible','off');
   set(t2fcia2,'visible','off');
   set(uni2,'visible','off');

case 2
   
   set(fcia1,'visible','on');
   set(fcia1,'string',0);
   set(fcia2,'visible','off');
   set(tfcia2,'visible','off');
   set(t2fcia2,'visible','off');
   set(uni2,'visible','off');
   
case 3
   
   set(fcia1,'visible','on');
   set(fcia1,'string',0);
   set(fcia2,'visible','on');
   set(fcia2,'string',0);
   set(tfcia2,'visible','on');
   set(t2fcia2,'visible','on');
   set(uni2,'visible','on');
   
case 4
   
   set(fcia1,'visible','on');
   set(fcia1,'string',0);
   set(fcia2,'visible','on');
   set(fcia2,'string',0);
   set(tfcia2,'visible','on');
   set(t2fcia2,'visible','on');
   set(uni2,'visible','on');
 
end

   %DISEÑO DE FILTROS
%TRABAJO FINAL CIRCUITOS II
%ROBINSON MONTES GOMEZ

function inicio();

f=findobj('Tag','met');
f=get(f,'Value');

max=findobj('tag','max');
min=findobj('tag','min');
max=finobj('tag','string');
min=finobj('tag','string');
max=str2num(max);
min=str2num(min)
fcia1=findobj('tag','fcia1');
fcia2=findobj('tag','fcia2');
fcia1=get(fcia1,'string');
fcia2=get(fcia2,'string');
fcia1=str2num(fcia1);
fcia2=str2num(fcia2);

tipo1=findobj(0,'Tag','filt');
tipo=get(tipo1,'Value');

[J,K]=imread('atenea.jpg');

if tipo == 1,
	if isempty(fcia1) | fcia1<=0,
		msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W1 MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
		return;
	end
	  
elseif tipo == 2,
	if isempty(fcia1) | fcia1<=0,
		msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W1 MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
		return;
	end
	
elseif tipo == 3,
	if isempty(fcia1) | fcia1<=0, 
		msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W1 MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
		return;
	end
	
	if isempty(fcia2) | fcia2<=0,
		msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W2 MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
		return;
	end
    
    if fcia2<=fcia1
        msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W2 MAYOR QUE W1','ADVERTENCIA','custom',J,K);
        return;
    end

elseif tipo == 4,
	if isempty(fcia1) | fcia1<=0, 
		msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W1 MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
		return;
	end
	
	if isempty(fcia2) | fcia2<=0,
		msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W2 MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
		return;
	end
    
    if fcia2<=fcia1
        msgbox('DEBEN INGRESAR VALORES CON UNA FRECUENCIA W2 MAYOR QUE W1','ADVERTENCIA','custom',J,K);
        return;
    end

            p=get(max,'string');
				if isempty(max) | max<=0,
				   msgbox('INGRESE EL VALOR DE Amax MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
				   return;
				end
		     	p=str2num(p);
           	
            if isempty(p),
		   	  msgbox('SOLO SE ACEPTAN VALORES NUMERICOS','ADVERTENCIA','custom',J,K);
			     return;
             end
             
             q=get(min,'string');
                if isempty(min) | min<=0,
                    msgbox('INGRESE EL VALOR DE Amin MAYOR QUE CERO','ADVERTENCIA','custom',J,K);
                    return;
                end
                q=str2num(q)
           	    
                if isempty(q),
		   	  msgbox('SOLO SE ACEPTAN VALORES NUMERICOS.','ADVERTENCIA','custom',J,K);
			     return;
			  	end
            end
                
